version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/project
    steps:
      # checkout the repository
      - checkout
      
      # run htmlproofer
      - run:
          name: test our generated HTML files
          command: |
            htmlproofer ~/project/src --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
